<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Nom_aNjali" failures="1" tests="2" name="MTRtestCase132_2019" time="203.085" errors="0" timestamp="22 Jan 2020 18:01:25 GMT">
  <testcase classname="com.nomisma.SAMTR_Scripts2019.MTRTestScenario132" name="funcAddTestCase132" time="59.372">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at com.nomisma.SelfAssessmentpom2019.SAPOM2019.calculateDividentFrmUKCompany1(SAPOM2019.java:9727)
	at com.nomisma.SelfAssessmentpom2019.SAPOM2019.addTestCase132(SAPOM2019.java:24616)
	at com.nomisma.SAMTR_Scripts2019.MTRTestScenario132.funcAddTestCase132(MTRTestScenario132.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- funcAddTestCase132 -->
  <testcase classname="com.nomisma.SAMTR_Scripts2019.MTRTestScenario132" name="funcDelTestCase132" time="117.978"/>
</testsuite> <!-- MTRtestCase132_2019 -->
